[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
arcium_encrypted_compute = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"